env:
  GRADLE_EXTRA_OPTS: -Preckon.scope=minor -Preckon.stage=final

jobs:
  assemble:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Assemble
        run: ./gradlew assemble $GRADLE_EXTRA_OPTS

on:
  push:
    branches:
      - main
    tags:
      - "*"
