jobs:
  assemble:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Assemble
        run: ./gradlew assemble $GRADLE_EXTRA_OPTS

on:
  pull_request:
    branches:
      - main
